### ISSUE TITLE
Toujours en developpement?

### ISSUE THREAD

**Issue by Clam29** [AmarOk1412/RORI_old#1]
Bonjour,
Je suis tombé sur RORI sur OpenClassroom, le projet date un peu désormais, mais je voulais savoir si tu étais toujours dessus? Cela m'interesse beaucoup :P

**Comment by AmarOk1412** [comment]
Il date oui, et faut que je le refasse en grande partie, je comptais faire ça dans l'année

**Comment by Clam29** [comment]
J'aurais quelques question du coup ^^
Tu fais comment pour l'installer sur ton pc?
Tu travaille sous linux a ce que j'ai compris?

**Comment by AmarOk1412** [comment]
Ouai je suis sur linux.

En fait je viens de remarquer que ce dépot n'est pas bon : va plutot ici : https://github.com/RORI-Chatterbot y a des wikis pour chaque projet

**Comment by Clam29** [comment]
Oki je vais y faire un tour :P

**Comment by AmarOk1412** [comment]
@Clam29 -> https://github.com/AmarOk1412/rori  ;)
